apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-pod
annotations:
    argocd.argoproj.io/sync-options: Replace=true    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-pod  
  template:
    metadata:
      labels:
        app: db-pod
    spec:
      containers:
      - name: db-pod
        image: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: api-db-configmap
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-db-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: api-db-configmap
              key: DB_NAME
        ports:
        - containerPort: 5432
        volumeMounts:                   
          - name: init-script
            mountPath: /docker-entrypoint-initdb.d
      volumes:                                
        - name: init-script
          configMap:
            name: postgres-init
---         
kind: Service
apiVersion: v1
metadata:
  name:  db-service
spec:
  selector:
    app:  db-pod
  type: ClusterIP
  ports:
  - name: tcp
    port:  5432
    targetPort:  5432   